services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - mongo
      - redis

  worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: celery -A worker.celery_worker worker --loglevel=info
    env_file:
      - ./backend/.env
    depends_on:
      - redis
      - mongo

  redis:
    image: redis:6

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    depends_on:
      - backend
