services:
  api:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - mongo
      - redis

  worker:
    build: .
    command: celery -A worker.celery_worker worker --loglevel=info
    env_file:
      - .env
    depends_on:
      - redis
      - mongo

  redis:
    image: redis:6

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
